### ISSUE TITLE
2to3?

### ISSUE THREAD

**Issue by RhysU** [SteveDiamond/parser#1]
My dumb attempts to get this going under Python 3 via 2to3 are failing.  Any chance you'd be willing to update it?

**Comment by RhysU** [comment]
More concretely, I'm seeing
```
In [1]: from dcp_parser.parser import Parser
  File "/home/rhys/Build/dcparser/dcp_parser/parser.py", line 4
    from . import atomic.atom_loader
                        ^
SyntaxError: invalid syntax
```
after 2to3.  And it's got to be simple but I'm all thumbs here.

**Comment by SteveDiamond** [comment]
2to3 works fine for me. I don't get this error. You must be using an old version of something.

**Comment by RhysU** [comment]
I see the error at runtime, not during 2to3:
```
$ python --version
Python 3.5.2 :: Anaconda 4.2.0 (64-bit)

$ git clone https://github.com/SteveDiamond/parser.git

$ cd parser/

$ 2to3 -w **/*.py

$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    from dcp_parser.parser import Parser
  File "/home/rhys/tmp/parser/dcp_parser/parser.py", line 4
    from . import atomic.atom_loader
                        ^
SyntaxError: invalid syntax
```

The problems appear to be from statements like `from . import foo.bar` and should read `from .foo import bar`.  There were, IIRC, two spots where I had to fix this after the conversion.

**Comment by SteveDiamond** [comment]
I see, my mistake. 2to3 isn't magical. You often need to fix a few issues like this. Does it work for you now?

**Comment by RhysU** [comment]
It does. Would you entertain a pull request to make the python 2 logic work unmodified after 2to3?

**Comment by SteveDiamond** [comment]
Sure, as long as it still passes all the tests in Python 2.
